In [2]:
import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

In [3]:
books = pd.read_csv("C:/Users/Narsing/Downloads/Assigments data science/Recommendation System--Assignment/book.csv",encoding="latin1")
books

Unnamed: 0  User.ID                                         Book.Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
...          ...      ...                                                ...   
9995        9996   162121       American Fried: Adventures of a Happy Eater.   
9996        9997   162121                              Cannibal In Manhattan   
9997        9998   162121                    How to Flirt: A Practical Guide   
9998        9999   162121                                           Twilight   
9999       10000   162129                       Kids Say the Darndest Things   

      Book.Rating  
0               5  
1               3  
2               6  
3               8  
4               6  
...           ...  
9995            7  
9996            9  
9997            7  
9998            8  
9999            6  

[10000 rows x 4 columns]

In [4]:
books['Book.Rating'].unique()

array([ 5,  3,  6,  8,  7, 10,  9,  4,  1,  2], dtype=int64)

In [7]:
books.shape

(10000, 4)

In [9]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   10000 non-null  int64 
 1   User.ID      10000 non-null  int64 
 2   Book.Title   10000 non-null  object
 3   Book.Rating  10000 non-null  int64 
dtypes: int64(3), object(1)
memory usage: 312.6+ KB


In [10]:
books.isna().sum()

Unnamed: 0     0
User.ID        0
Book.Title     0
Book.Rating    0
dtype: int64

In [12]:
books.duplicated().sum()

0

In [13]:
books.describe()

Unnamed: 0        User.ID  Book.Rating
count  10000.00000   10000.000000  10000.00000
mean    5000.50000   95321.249800      7.56630
std     2886.89568  117645.703609      1.82152
min        1.00000       8.000000      1.00000
25%     2500.75000    2103.000000      7.00000
50%     5000.50000    3757.000000      8.00000
75%     7500.25000  162052.000000      9.00000
max    10000.00000  278854.000000     10.00000

In [14]:
books = books.iloc[:,1:]
books.head()

User.ID                                         Book.Title  Book.Rating
0   276726                                Classical Mythology            5
1   276729                                       Clara Callan            3
2   276729                               Decision in Normandy            6
3   276736  Flu: The Story of the Great Influenza Pandemic...            8
4   276737                             The Mummies of Urumchi            6

In [15]:
books = books.rename({'User.ID':'userId',
                     'Book.Title':'title',
                     'Book.Rating':'rating'},axis=1)
books.head()

userId                                              title  rating
0  276726                                Classical Mythology       5
1  276729                                       Clara Callan       3
2  276729                               Decision in Normandy       6
3  276736  Flu: The Story of the Great Influenza Pandemic...       8
4  276737                             The Mummies of Urumchi       6

In [16]:
len(books)

10000

In [17]:
len(books.userId.unique())

2182

In [18]:
len(books.title.unique())

9659

In [19]:
print(books.userId.nunique(),books.title.nunique())

2182 9659


In [20]:
books.title.unique()

array(['Classical Mythology', 'Clara Callan', 'Decision in Normandy', ...,
       'How to Flirt: A Practical Guide', 'Twilight',
       'Kids Say the Darndest Things'], dtype=object)

In [21]:
books.userId.unique()

array([276726, 276729, 276736, ..., 162113, 162121, 162129], dtype=int64)

In [22]:
books.rating.unique()

array([ 5,  3,  6,  8,  7, 10,  9,  4,  1,  2], dtype=int64)

### Popularity based

In [23]:
rating_count = books.groupby('title').count()['rating'].reset_index()
rating_count.rename(columns={'rating':'rating_count'},inplace=True)
rating_count.head()

title  rating_count
0                                Jason, Madison &amp             1
1          Other Stories;Merril;1985;McClelland &amp             1
2                           Repairing PC Drives &amp             1
3                                                '48             1
4  'O Au No Keia: Voices from Hawai'I's Mahu and ...             1

In [24]:
AvgRating_count = books.groupby('title').mean()['rating'].reset_index()
AvgRating_count.rename(columns={'rating':'Avg_rating'},inplace = True)
AvgRating_count.head()

title  Avg_rating
0                                Jason, Madison &amp         8.0
1          Other Stories;Merril;1985;McClelland &amp         6.0
2                           Repairing PC Drives &amp         4.0
3                                                '48         7.0
4  'O Au No Keia: Voices from Hawai'I's Mahu and ...         8.0

In [25]:
popular_df=rating_count.merge(AvgRating_count,on='title')
popular_df

title  rating_count  \
0                                   Jason, Madison &amp             1   
1             Other Stories;Merril;1985;McClelland &amp             1   
2                              Repairing PC Drives &amp             1   
3                                                   '48             1   
4     'O Au No Keia: Voices from Hawai'I's Mahu and ...             1   
...                                                 ...           ...   
9654  \Surely You're Joking, Mr. Feynman!\: Adventur...             1   
9655             \Well, there's your problem\: Cartoons             1   
9656                            iI Paradiso Degli Orchi             1   
9657                                           stardust             1   
9658                                     Ã?Â?bermorgen.             1   

      Avg_rating  
0            8.0  
1            6.0  
2            4.0  
3            7.0  
4            8.0  
...          ...  
9654         8.0  
9655         9.0  
9656         7.0  
9657         5.0  
9658         4.0  

[9659 rows x 3 columns]

In [26]:
popular_df = popular_df.sort_values('Avg_rating',ascending = False).head(50)
popular_df

title  rating_count  \
2157  Dr Mommy (From Here To Maternity) (Silhouette ...             1   
8108                           The Piano Man's Daughter             1   
5564                                  Private Screening             1   
8114  The Pilates Body: The Ultimate At-Home Guide t...             1   
1959                                   Desert Solitaire             1   
8117                           The Pillars of the Earth             1   
5558                                Principia Discordia             1   
1175                                             COWBOY             1   
1960                                   Design for Dying             1   
7176                                         The Coming             1   
1172  COUNTERFEIT CHRISTMAS (NANCY DREW FILES 102) :...             1   
8120                         The Pilot's Wife : A Novel             1   
5551                                   Prince of Wolves             1   
5550                                   Prince of Whales             1   
3311                          Hoot (Newbery Honor Book)             1   
1167                                   CHILD IS BORN, A             1   
8123                          The Pink Flamingo Murders             1   
1164  CCNA: Cisco Certified Network Associate Study ...             1   
7172                                The Colors of Space             1   
3314                                      Hornet's Nest             1   
1161                     CALIBAN COVE: RESIDENT EVIL #2             1   
6343                                Soldiers Of Fortune             1   
1965                       Desserts (Merehurst Cookery)             1   
7169                              The Color of Distance             1   
6344                         Solo: On Her Own Adventure             1   
5567            Prize Stories, 1987: The O'Henry Awards             1   
8107                     The Piano Lesson (Plume Drama)             1   
5535  Pride and Prejudice (Everyman Paperback Classics)             1   
1184                                            CYCLOPS             1   
2630         Fiesta! A Celebration of Latin Hospitality             1   
2629                                Fiddleback: A Novel             1   
3277  Hollywood Speaks: Deafness and the Film Entert...             1   
1205  Calliope's Sisters: A Comparative Study of Phi...             1   
8074                             The Passion of Molly T             1   
3278           Holy Fire: A Novel (Bantam Spectra Book)             1   
7187              The Complete Hot &amp; Spicy Cookbook             1   
1955                              Des Teufels Kardinal.             1   
8082                                          The Pearl             1   
5577                                              Proof             1   
8085             The Peculiar Memories of Thomas Penman             1   
8093              The Peppermint Pig (Yearling Classic)             1   
6334                                  So Worthy My Love             1   
7181  The Complete Bolivian Diaries of Che Guevara, ...             1   
8097  The Perfect Storm: A True Story of Men Against...             1   
5575  Promises Broken (Caitlin: The Promise Trilogy,...             1   
8099                            The Persian Pickle Club             1   
3290  Homeschoolers' Success Stories : 15 Adults and...             1   
1189          Cadaveres Exquisitos (Biblioteca del sur)             1   
3291  Homeschooling: The Teen Years : Your Complete ...             1   
5571                           Programming the Perl DBI             1   

      Avg_rating  
2157        10.0  
8108        10.0  
5564        10.0  
8114        10.0  
1959        10.0  
8117        10.0  
5558        10.0  
1175        10.0  
1960        10.0  
7176        10.0  
1172        10.0  
8120        10.0  
5551        10.0  
5550        10.0  
3311        10.0  
1167        10.0  
812

### Collaborative system

In [27]:
final_df = books.pivot_table(index='title',columns='userId',values='rating')
final_df.fillna(0,inplace=True)
final_df

userId                                              8       9       10      \
title                                                                        
 Jason, Madison &amp                                   0.0     0.0     0.0   
 Other Stories;Merril;1985;McClelland &amp             0.0     0.0     0.0   
 Repairing PC Drives &amp                              0.0     0.0     0.0   
'48                                                    0.0     0.0     0.0   
'O Au No Keia: Voices from Hawai'I's Mahu and T...     0.0     0.0     0.0   
...                                                    ...     ...     ...   
\Surely You're Joking, Mr. Feynman!\: Adventure...     0.0     0.0     0.0   
\Well, there's your problem\: Cartoons                 0.0     0.0     0.0   
iI Paradiso Degli Orchi                                0.0     0.0     0.0   
stardust                                               0.0     0.0     0.0   
Ã?Â?bermorgen.                                         0.0     0.0     0.0   

userId                                              12      14      16      \
title                                                                        
 Jason, Madison &amp                                   0.0     0.0     0.0   
 Other Stories;Merril;1985;McClelland &amp             0.0     0.0     0.0   
 Repairing PC Drives &amp                              0.0     0.0     0.0   
'48                                                    0.0     0.0     0.0   
'O Au No Keia: Voices from Hawai'I's Mahu and T...     0.0     0.0     0.0   
...                                                    ...     ...     ...   
\Surely You're Joking, Mr. Feynman!\: Adventure...     0.0     0.0     0.0   
\Well, there's your problem\: Cartoons                 0.0     0.0     0.0   
iI Paradiso Degli Orchi                                0.0     0.0     0.0   
stardust                                               0.0     0.0     0.0   
Ã?Â?bermorgen.                                         0.0     0.0     0.0   

userId                                              17      19      22      \
title                                                                        
 Jason, Madison &amp                                   0.0     0.0     0.0   
 Other Stories;Merril;1985;McClelland &amp             0.0     0.0     0.0   
 Repairing PC Drives &amp                              0.0     0.0     0.0   
'48                                                    0.0     0.0     0.0   
'O Au No Keia: Voices from Hawai'I's Mahu and T...     0.0     0.0     0.0   
...                                                    ...     ...     ...   
\Surely You're Joking, Mr. Feynman!\: Adventure...     0.0     0.0     0.0   
\Well, there's your problem\: Cartoons                 0.0     0.0     0.0   
iI Paradiso Degli Orchi                                0.0     0.0     0.0   
stardust                                               0.0     0.0     0.0   
Ã?Â?bermorgen.                                         0.0     0.0     0.0   

userId                                              26      ...  278831  \
title                                                       ...           
 Jason, Madison &amp                                   0.0  ...     0.0   
 Other Stories;Merril;1985;McClelland &amp             0.0  ...     0.0   
 Repairing PC Drives &amp                              0.0  ...     0.0   
'48                                                    0.0  ...     0.0   
'O Au No Keia: Voices from Hawai'I's Mahu and T...     0.0  ...     0.0   
...                                                    ...  ...     ...   
\Surely You're Joking, Mr. Feynman!\: Adventure...     0.0  ...     0.0   
\Well, there's your problem\: Cartoons                 0.0  ...     0.0   
iI Paradiso Degli Orchi                                0.0  ...     0.0   
stardust                                               0.0  ...     0.0   
Ã?Â?bermorgen.                                         

In [28]:
similarity_score = cosine_similarity(final_df)
similarity_score.shape

(9659, 9659)

In [29]:
similarity_score

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
np.where(final_df.index=='Classical Mythology')[0][0]

1443

In [35]:
def recommend(book):
    book_index = np.where(final_df.index==book)[0][0]
    distances = similarity_score[book_index]
    book_list = sorted(list(enumerate(distances)),reverse = True,key = lambda x:x[1])[1:6]
    
    for i in book_list:
            print(final_df.index[i[0]])

In [36]:
recommend('Classical Mythology')

 Jason, Madison &amp
 Other Stories;Merril;1985;McClelland &amp
 Repairing PC Drives &amp
'48
'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities


In [37]:
recommend('COWBOY')

30: Pieces of a Novel
A More Perfect Union
A Nest of Ninnies
A Pinch of Snuff
A Valentine Wedding
